#!/bin/bash

# Custom Rofi Script

BORDER="#FF000000"
SEPARATOR="#00000000"
FOREGROUND="#FFFFFF"
BACKGROUND="#FF000000"
BACKGROUND_ALT="#FF000000"
HIGHLIGHT_BACKGROUND="#59000000"
HIGHLIGHT_FOREGROUND="#1e88e5"

YELLOW="#fdd835"
MAGENTA="#00897b"

# Launch Rofi
rofi -no-lazy-grab -show drun \
-display-drun "App" -drun-display-format "{name}" \
-hide-scrollbar true \
-bw 0 \
-lines 10 \
-line-padding 10 \
-padding 20 \
-width 30 \
-xoffset 0 -yoffset -44 \
-location 7 \
-columns 2 \
-show-icons -icon-theme "Paper" \
-font "Noto Sans 11.5" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND"

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
