#!/bin/bash

# Custom Rofi Script

BORDER="#FF000000"
SEPARATOR="#00000000"
FOREGROUND="#FFFFFF"
BACKGROUND="#FF000000"
BACKGROUND_ALT="#00000000"
HIGHLIGHT_BACKGROUND="#59000000"
HIGHLIGHT_FOREGROUND="#1e88e5"

YELLOW="#fdd835"
MAGENTA="#00897b"

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System' \
-hide-scrollbar true \
-bw 0 \
-lines 4 \
-line-padding 8 \
-padding 20 \
-width 15 \
-xoffset 0 -yoffset -44 \
-location 5 \
-columns 1 \
-show-icons -icon-theme "Papirus" \
-font "Noto Sans 9" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< "Lock|Logout|Reboot|Shutdown")"
case "$MENU" in
  *Lock) /home/nick/Projects/Scripts/lock.sh ;;
  *Logout) bspc quit ;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac
